W4D5/music_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show]

  resources :bands, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :albums, only: :new
  end
  
  resources :albums, only: [:show, :create, :edit, :update, :destroy]

  resource :session, only: [:new, :create, :destroy]
end

W4D5/music_app/app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :bigint(8)        not null, primary key
#  title      :string           not null
#  band_id    :integer          not null
#  year       :integer          not null
#  live       :boolean          default(FALSE), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Album < ApplicationRecord
  validates :title, :band_id, :year, presence: true
  validates_inclusion_of :year, in: 1951..Time.current.year

  belongs_to :band,
    foreign_key: :band_id,
    class_name: :Band
end

W4D5/music_app/app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :bigint(8)        not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Band < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many :albums,
    foreign_key: :band_id,
    class_name: :Album
end

W4D5/music_app/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint(8)        not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  validates :email, :session_token, presence: true, uniqueness: true
  validates :password_digest, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }

  attr_reader :password
  after_initialize :ensure_session_token

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    return nil if user.nil?
    if user.is_password?(password)
      user
    else
      nil
    end
  end

  def self.generate_session_token
    SecureRandom.urlsafe_base64(16)
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end
end

W4D5/music_app/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def show
    @album = Album.find(params[:id])
    render :show
  end

  def new
    @album = Album.new(band_id: params[:band_id])
    render :new
  end

  def create
    @album = Album.new(album_params)

    if @album.save
      redirect_to album_url(@album)
    else
      flash.now[:errors] = @album.errors.full_messages
      render :new
    end
  end

  def edit
    @album = Album.find(params[:id])
    render :edit
  end

  def update
    @album = Album.find(params[:id])
    if @album.update(album_params)
      redirect_to album_url(@album)
    else
      flash.now[:errors] = @album.errors.full_messages
      render :edit
    end
  end

  def destroy
    album = Album.find(params[:id])
    band = @album.band
    album.destroy
    redirect_to band_url(band)
  end

  private
  def album_params
    params.require(:album).permit(:title, :band_id, :year, :live)
  end
end

W4D5/music_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :logged_in?, :current_user

  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    !!@current_user
  end

  def log_in_user!(user)
    session[:session_token] = user.reset_session_token!
  end

  def log_out_user!
    current_user.reset_session_token!
    session[:session_url] = nil
  end
end

W4D5/music_app/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def index
    @bands = Band.all
    render :index
  end

  def show
    @band = Band.find(params[:id])
    render :show
  end

  def new
    @band = Band.new
    render :new
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :new
    end
  end

  def edit
    @band = Band.find(params[:id])
    render :edit
  end

  def update
    @band = Band.find(params[:id])
    if @band.update(band_params)
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :edit
    end
  end

  def destroy
    @band = Band.find(params[:id])
    @band.destroy
    redirect_to bands_url
  end

  private
  def band_params
    params.require(:band).permit(:name)
  end
end

W4D5/music_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end

  def create
    user = User.find_by_credentials(
      [:user][:email],
      [:user][:password]
    )

    if user
      log_in_user(user)
      redirect_to user_url
    else
      flash.now[:errors] = ['Incorrect username and/or password.']
      render :new
    end
  end

  def destroy
    log_out_user!
    redirect_to new_session_url
  end
end

W4D5/music_app/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in_user!(@user)
      redirect_to user_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password)
  end
end

W4D5/music_app/app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token
    "<input
      type=\"hidden\"
      name=\"authenticity_token\"
      value='#{form_authenticity_token}'
    />".html_safe
  end
end

W4D5/music_app/app/views/albums/_form.html.erb
<p>by <%= album.band.name %></p>

<% if album.persisted? %>
  <% action = album_url(album) %>
  <% submit_txt = "Update" %>
  <a href="<%= album_url(album) %>">&lt--back</a>
<% else %>
  <% action = albums_url %>
  <% submit_txt = "Create" %>
  <a href="<%= band_url(album.band) %>">&lt--back</a>
<% end %>

<form action="<%= action %>" method="post">
  <%= auth_token %>
  <% if album.persisted? %>
    <input type="hidden" name="_method" value="patch">
  <% end %>

  <input type="hidden" name="album[band_id]" value="<%= album.band_id %>"

  <label for="title">Album title:</label>
  <input type="string" name="album[title]" id="title" value="<%= album.title %>">
  <br>

  <label for="year">Year:</label>
  <input type="integer" name="album[year]" id="year" value="<%= album.year %>">
  <br>

  <input type="radio" name="album[live]" value=false <%= album.live == false ? "checked" : "" %>>
  <label for="studiio">studio</label>

  <input type="radio" name="album[live]" value=true <%= album.live == true ? "checked" : "" %>>
  <label for="live">live</label>
  <br>

  <input type="submit" value="<%= submit_txt %>">
</form>

W4D5/music_app/app/views/albums/edit.html.erb
<%= render "form", album: @album %>

W4D5/music_app/app/views/albums/new.html.erb
<h2>New Album</h2>

<%= render "form", album: @album %>

W4D5/music_app/app/views/albums/show.html.erb
<h2>Album</h2>

<div class="float_left">
  <h3><%= @album.title %></h3>

  <a href="<%= edit_album_url(@album.id) %>">Edit</a>

  <form action="<%= album_url(@album.id) %>" method="post">
    <%= auth_token %>
    <input type="hidden" name="_method" value="delete">
    <input type="submit" value="Delete">
  </form>
</div>

<table>
  <tr>
    <th>Artist:</th>
    <th><a href="<%= band_url(@album.band) %>"><%= @album.band.name %></a></th>
  </tr>

  <tr>
    <th>Year:</th>
    <th><%= @album.year %></th>
  </tr>

  <tr>
    <th>Type:</th>

    <th>
      <% if @album.live %>
        Live
      <% else %>
        Studio
      <% end %>
    </th>

  </tr>
</table>

W4D5/music_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="float_left">
      <h1>Music App</h1>

      <% if logged_in? %>
        <%= current_user.email %>
        <form action="<%= session_url %>" method="post">
          <%= auth_token %>
          <input type="hidden" name="_method" value="destroy">
          <input type="submit" value="Sign-out">
        </form>
      <% else %>
        <a href="<%= new_session_url %>">Login</a>
        <a href="<%= new_user_url %>">Signup</a>
      <% end %>
    </div>

    <% if flash[:errors] %>
      <ul>
        <% flash[:errors].each do |error| %>
          <li><%= error %></li>
        <% end %>
      </ul>
    <% end %>

    <%= yield %>
  </body>
</html>

W4D5/music_app/app/views/users/new.html.erb
<h2>Sign Up</h2>